ARG  IMAGE_VERSION
FROM aproint/aws-codebuild-serverless:${IMAGE_VERSION}

RUN yum install -y git unzip jq

RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" && \
    unzip awscli-bundle.zip && \
    ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

CMD []
