#!/bin/bash
node=(6.10.3 8.10.0)
serverless=(1.27.3 1.28.0)

for node_version in "${node[@]}"
do
    for serverless_version in "${serverless[@]}"
    do
        node_major=$(echo $node_version | awk -F. 'print $1')
        sls_minor=$(echo $node_version | awk 'BEGIN{FS=OFS="."}{NF--; print}')
        tag_prefix="node${node_major}-sls"
        tag_all="${tag_prefix}-${serverless_version}"
        tag_minor="${tag_prefix}-${sls_minor}"
        docker build \
            --build-arg NODE_VERSION=$node_version \
            --build-arg SERVERLESS_VERSION=$serverless_version \
            -f $DOCKERFILE_PATH \
            -t $IMAGE_NAME \
            -t $DOCKER_REPO:$tag_all
            -t $DOCKER_REPO:$tag_minor
            .
    done
done